export PATH="$HOME/.local/share/nvim/mason/bin/:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
alias ls="lsd"
alias lst="lsd --tree --depth 3"
alias py="python3"
alias nv="nvim"
alias tm="tmux"
alias neofetch="neofetch --source /home/ira/.config/nefetch/logo.txt"
alias ":q"="exit"
alias "cd.."="cd .."
#alias obs="flatpak run md.obsidian.Obsidian"
#alias postman="flatpak run com.getpostman.Postman"
#alias pycharm="flatpak run com.jetbrains.PyCharm-Community"
#alias pixel-dungeon="flatpak run com.shatteredpixel.shatteredpixeldungeon"
alias poweroff="systemctl poweroff"
alias docker_clear="$HOME/configs/scripts/clear_all_containers.sh"
alias copy_configs="$HOME/configs/scripts/copy_configs.sh"
alias "git_log"="git log --graph  --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%C(auto)%d%C(reset)' --all"
#source $HOME/configs/scripts/volume_and_brightness_notifications
